name: win32_runner
description: | 
  Compile and run a Flutter app without needing any C/C++ code. Just Dart!
version: 0.1.1
repository: https://github.com/dart-windows/win32_runner
homepage: https://win32.pub

topics:
  - ffi
  - windows

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  windows:

dependencies:
  args: ^2.4.0
  ffi: ^2.0.1
  win32: ^5.0.0

dev_dependencies:
  dartwindows_lints: ^1.0.0
  melos: ^3.1.1
  test: ^1.24.6
