name: win32_runner
description: >
  Compile and run a Flutter app without needing any C/C++ code. Just Dart!
version: 0.1.2
homepage: https://win32.pub
repository: https://github.com/dart-windows/win32_runner
issue_tracker: https://github.com/dart-windows/win32_runner/issues

topics:
  - win32
  - ffi
  - windows

environment:
  sdk: '^3.1.0'

platforms:
  windows:

dependencies:
  args: ^2.4.2
  ffi: ^2.1.0
  win32: ^5.0.7

dev_dependencies:
  dartwindows_lints: ^1.0.0
  melos: ^3.1.1
  test: ^1.24.6
