name: win32_runner
description: Run a Flutter app without needing a lick of C/C++ code. Just Dart!
version: 0.0.3
repository: https://github.com/timsneath/win32_runner

environment:
  sdk: '>=2.15.0 <3.0.0'

platforms:
  windows:

dependencies:
  args: ^2.3.0
  ffi: ^1.1.2
  win32: ^2.3.9

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
