name: win32_runner
description: | 
  Compile and run a Flutter app without needing any C/C++ code. Just Dart!
version: 0.1.0
repository: https://github.com/timsneath/win32_runner

topics:
  - ffi
  - windows

environment:
  sdk: '>=3.0.0-417.0 <4.0.0'

platforms:
  windows:

dependencies:
  args: ^2.4.0
  ffi: ^2.0.1
  win32: ^4.1.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
